$(document).ready(function(){
  $(".owl-carousel").owlCarousel({
    margin:50,
    loop:true,
    autoplay:true,
    autoplayTimeout:3000,
    responsive:{
      0:{
          items:1,
          nav:true,
      },
      600:{
          items:2,
          nav:true
      },
      1000:{
          items:2,
          nav:true,
          loop:true
      }
  }
  });
});